apiVersion: apps/v1
kind: Deployment
metadata:
  name: helldivers2-bot-deployment
  namespace: helldivers2
  labels:
    app: helldivers2-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helldivers2-bot
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: helldivers2-bot
    spec:
      containers:
        - name: helldivers2-bot
          image: ghcr.io/jgaribsin/helldivers2-bot:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 500Mi
              cpu: 100m
          env:
            - name: NODE_ENV
              value: 'production'
            - name: BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: BOT_TOKEN
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: DATABASE_URL
            - name: NEW_RELIC_APP_NAME
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: NEW_RELIC_APP_NAME
            - name: NEW_RELIC_LICENSE_KEY
              valueFrom:
                secretKeyRef:
                  name: bot-secrets
                  key: NEW_RELIC_LICENSE_KEY
      imagePullSecrets:
        - name: regcred
